ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

== Memcached Operator Example built using Kubebuilder

ifdef::status[]
.*Project health*
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://goreportcard.com/badge/github.com/dev4devs-com/memcached-kubebuilder[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/dev4devs-com/postgresql-operator]
endif::[]

:toc:
toc::[]

== Overview

Simple example over how to know how getting started with Kubebuilder

== Prerequisites

|===
|https://golang.org/doc/install[Install Golang] v1.12+
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[Install kubectl]
|Access to a Kubernetes v1.11.3+ cluster
|===

The following prerequisite is just required if you would like to contribute with.

|===
|https://book.kubebuilder.io/quick-start.html#installation[kubebuilder]
|===

== Getting Started

=== Cloning the repository

By the following commands you will create a local directory and clone this project.

[source,shell]
----
$ git clone git@github.com:dev4devs-com/memcached-kubebuilder.git $GOPATH/src/github.com/dev4devs-com/memcached-kubebuilder
----

=== [Optional] Minishift installation and setup

https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then enable Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# add insecure registry to download the images from docker
$ minishift config set insecure-registry 172.30.0.0/16

# start the instance
$ minishift start
----

IMPORTANT: Please, feel free to use https://kubernetes.io/docs/setup/learning-environment/minikube/[Minikube] your any Kubernetes cluster as you wish.

=== Installing as standalone

Use the following command to install the Operator(Manager) and the Memcached example CR.

NOTE: To install you need be logged in as a user with cluster privileges like the `system:admin` user. E.g. By using: `oc login -u system:admin`.

[source,shell]
----
$ make app/install
----

=== Verifying

To verify that the installation was successful completed you can check the `deployment.apps/controller-manager` and `deployment.apps/memcached-sample` were created and are running. Following an example of the expected result when all is applied.

```shell
 $ kubectl get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/controller-manager-bd74bb8f8-dvgxc   1/1     Running   0          14m
pod/memcached-sample-7484db9bc9-88bh8    1/1     Running   0          13m


NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/controller-manager-metrics-service   ClusterIP   172.30.161.134   <none>        8443/TCP    14m
service/memcached-sample                     ClusterIP   172.30.148.254   <none>        11211/TCP   13m


NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/controller-manager   1         1         1            1           14m
deployment.apps/memcached-sample     1         1         1            1           13m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/controller-manager-bd74bb8f8   1         1         1       14m
replicaset.apps/memcached-sample-7484db9bc9    1         1         1       13m
```

=== Uninstalling

Use the following command will delete all since it will remove the namespace where all was installed.

[source,shell]
----
$ make app/uninstal
----

NOTE: To uninstall you need be logged in as a user with cluster privileges like the `system:admin` user. E.g. By using: `oc login -u system:admin`.

== Contributing

All contributions are hugely appreciated. Please see our link:./CONTRIBUTING.md[Contribution Guide] for guidelines on how to open issues and pull requests. Please check out our link:./CODE_OF_CONDUCT.md[Code of Conduct] too.
